### ISSUE TITLE
Make this a multi-module project

### ISSUE THREAD

**Issue by hosszubalazs** [SonarSource/SonarTS-example#1]
Since SonarTS 1.1 has improved support for multi-module setups, it would be great to demonstrate that here.

**Comment by vilchik-elena** [comment]
@hosszubalazs So cool to get feedback on this repo, thanks! We will try to add more projects asap (that you can guess as we have existing examples holding name `example1`)  and thanks for your issue SonarSource/SonarTS#259 which is probably related to this one

**Comment by saberduck** [comment]
@hosszubalazs @vilchik-elena I think we can close this issue? `example2` is using gradle build and multi-module project.
