### ISSUE TITLE
Coverage is published to Sonar but issues and code smell are not

### ISSUE THREAD

**Issue by damianszczepanik** [SonarSource/SonarTS-example#6]
I was able to run `example1` project and the code coverage is published on Sonar. However I could not process code static analyses so issues are not published on Sonar.

What should I do to make sure that project takes rules from Sonar (based on logs I believe this is happening right now) and send issues back to Sonar once the analyses is done?

What makes me worry now is an error:
```
15:49:10.063 ERROR: No valid rules have been specified for TypeScript files
```
however rules are available on Sonar and also TS profile is listed on project dashboard
```
Quality Profiles
(TypeScript) myCompany Way
```

**Comment by vilchik-elena** [comment]
@damianszczepanik Could you show full logs? 
Are you sure your profile is not empty?:)

**Comment by damianszczepanik** [comment]
I found that sonar-scanner version was older than SonarTS plugin and because of unknown reason Java worked fine while TypeScript didn't. Once the sonar-scanner was upgraded everything seems to be working. Or rather I have some problems but rather not related to SonarTS
